# Generated by Django 5.0.2 on 2025-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(upload_to='submissions/'),
        ),
    ]
