# Generated by Django 5.0.2 on 2025-04-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_submission_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='human_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
